site_name: Kraken Project Docs
site_url: "https://docs.kraken-project.org/"
theme:
  name: material
  logo: "assets/kraken_logo.png"
  favicon: "assets/favicon.svg"
  icon:
    repo: "fontawesome/brands/github"
  custom_dir: overrides
  features:
    - content.tabs.link
    - content.code.annotate
    - toc.follow
    - toc.integrate
    - navigation.tabs
    - navigation.top
  palette:
    scheme: slate
    primary: black
repo_url: https://github.com/myOmikron/kraken-project
repo_name: myOmikron/kraken-project
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
      - "../vagrant/example.vars.yml"
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  version:
    provider: mike
nav:
  - Home: index.md
  - Installation: installation/index.md
  - Administration: administration/index.md
  - User guide: user/index.md
  - Contribution:
    - General information: contribution/index.md
    - Development Enviornment: contribution/dev_setup.md
    - Style guidelines:
      - Rust: contribution/rust.md
      - Typescript: contribution/typescript.md
